# Generated by Django 3.1.7 on 2021-04-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20210330_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
    ]
