# Generated by Django 3.1.7 on 2021-04-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20210416_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='city_id',
            new_name='city',
        ),
    ]
