# Generated by Django 3.1.7 on 2021-03-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=20)),
                ('population_type', models.CharField(choices=[('l', 'Low'), ('m', 'Middle'), ('u', 'Upper-middle'), ('h', 'High')], max_length=1)),
                ('price', models.FloatField()),
                ('fuel_type', models.CharField(choices=[('g', 'Gasoline'), ('d', 'Diesel'), ('b', 'Bio Diesel'), ('e', 'Ethanol'), ('o', 'Other')], max_length=1)),
                ('status', models.CharField(choices=[('n', 'New'), ('u', 'Used')], default='n', max_length=1)),
                ('doors', models.IntegerField()),
                ('capacity', models.FloatField()),
                ('gear_case', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=15)),
                ('slug', models.CharField(max_length=20)),
                ('sitting_place', models.IntegerField(default=2)),
                ('first_registration_date', models.DateTimeField()),
                ('engine_power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Car photo')),
                ('position', models.CharField(max_length=30)),
                ('metadata', models.CharField(max_length=30)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', 'Opened'), ('c', 'Closed')], default='o', max_length=1)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=255)),
                ('car_id', models.ForeignKey(on_delete=models.SET('Sold'), to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.property')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.model'),
        ),
    ]
