# Generated by Django 3.1.7 on 2021-04-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210408_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='dealer_id',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='carproperty',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carproperty',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='car_id',
            new_name='car',
        ),
    ]
