# Generated by Django 3.1.7 on 2021-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
